/**
 * This is an external javascript file used by the custom stylesheet code to call the external 
 * javascript functions for rendering secure dynamic navigation.
 */

function h(a){throw a;}
var i=void 0,n=null,o,q=this,aa=function(){},ba=function(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&
!a.propertyIsEnumerable("call"))return"function"}else return"null";else if(b=="function"&&typeof a.call=="undefined")return"object";return b},r=function(a){return ba(a)=="array"},ca=function(a){var b=ba(a);return b=="array"||b=="object"&&typeof a.length=="number"},s=function(a){return typeof a=="string"},da=function(a){return ba(a)=="function"},ea=function(a){a=ba(a);return a=="object"||a=="array"||a=="function"},ha=function(a){return a[fa]||(a[fa]=++ga)},fa="closure_uid_"+Math.floor(Math.random()*
2147483648).toString(36),ga=0,ia=function(a){return a.call.apply(a.bind,arguments)},ja=function(a,b){var c=b||q;if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var b=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(b,d);return a.apply(c,b)}}else return function(){return a.apply(c,arguments)}},t=function(){t=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?ia:ja;return t.apply(n,arguments)},u=Date.now||
function(){return+new Date},w=function(a,b){function c(){}c.prototype=b.prototype;a.d=b.prototype;a.prototype=new c};Function.prototype.bind=Function.prototype.bind||function(a){if(arguments.length>1){var b=Array.prototype.slice.call(arguments,1);b.unshift(this,a);return t.apply(n,b)}else return t(this,a)};var ka=function(a){this.stack=Error().stack||"";if(a)this.message=String(a)};w(ka,Error);ka.prototype.name="CustomError";var la=function(a){for(var b=1;b<arguments.length;b++)var c=String(arguments[b]).replace(/\$/g,"$$$$"),a=a.replace(/\%s/,c);return a},ra=function(a){if(!ma.test(a))return a;a.indexOf("&")!=-1&&(a=a.replace(na,"&amp;"));a.indexOf("<")!=-1&&(a=a.replace(oa,"&lt;"));a.indexOf(">")!=-1&&(a=a.replace(pa,"&gt;"));a.indexOf('"')!=-1&&(a=a.replace(qa,"&quot;"));return a},na=/&/g,oa=/</g,pa=/>/g,qa=/\"/g,ma=/[&<>\"]/,sa=function(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,
"\\x08")},ua=function(a,b){for(var c=0,d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=String(b).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=Math.max(d.length,e.length),g=0;c==0&&g<f;g++){var j=d[g]||"",k=e[g]||"",l=RegExp("(\\d*)(\\D*)","g"),v=RegExp("(\\d*)(\\D*)","g");do{var m=l.exec(j)||["","",""],p=v.exec(k)||["","",""];if(m[0].length==0&&p[0].length==0)break;c=ta(m[1].length==0?0:parseInt(m[1],10),p[1].length==0?0:parseInt(p[1],10))||ta(m[2].length==0,p[2].length==0)||ta(m[2],
p[2])}while(c==0)}return c},ta=function(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};var wa=function(a,b){b.unshift(a);ka.call(this,la.apply(n,b));b.shift();this.Zc=a};w(wa,ka);wa.prototype.name="AssertionError";var x=function(a,b){if(!a){var c=Array.prototype.slice.call(arguments,2),d="Assertion failed";if(b){d+=": "+b;var e=c}h(new wa(""+d,e||[]))}};var y=Array.prototype,z=y.indexOf?function(a,b,c){x(a.length!=n);return y.indexOf.call(a,b,c)}:function(a,b,c){c=c==n?0:c<0?Math.max(0,a.length+c):c;if(s(a)){if(!s(b)||b.length!=1)return-1;return a.indexOf(b,c)}for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},xa=y.forEach?function(a,b,c){x(a.length!=n);y.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=s(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},ya=y.filter?function(a,b,c){x(a.length!=n);return y.filter.call(a,b,
c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=s(a)?a.split(""):a,j=0;j<d;j++)if(j in g){var k=g[j];b.call(c,k,j,a)&&(e[f++]=k)}return e},za=y.map?function(a,b,c){x(a.length!=n);return y.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=s(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e},Aa=function(a,b){z(a,b)>=0||a.push(b)},Ba=function(){return y.concat.apply(y,arguments)},Ca=function(a){if(r(a))return Ba(a);else{for(var b=[],c=0,d=a.length;c<d;c++)b[c]=
a[c];return b}},Ea=function(a){x(a.length!=n);y.splice.apply(a,Da(arguments,1))},Da=function(a,b,c){x(a.length!=n);return arguments.length<=2?y.slice.call(a,b):y.slice.call(a,b,c)};var Fa=function(a,b){this.x=a!==i?a:0;this.y=b!==i?b:0};Fa.prototype.toString=function(){return"("+this.x+", "+this.y+")"};var Ga=function(a,b){this.width=a;this.height=b};Ga.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};Ga.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};Ga.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};var Ha=function(a,b){for(var c in a)b.call(i,a[c],c,a)},Ja=function(){var a=Ia,b;for(b in a)return!1;return!0},Ka=["constructor","hasOwnProperty","isPrototypeOf","propertyIsEnumerable","toLocaleString","toString","valueOf"],La=function(a){for(var b,c,d=1;d<arguments.length;d++){c=arguments[d];for(b in c)a[b]=c[b];for(var e=0;e<Ka.length;e++)b=Ka[e],Object.prototype.hasOwnProperty.call(c,b)&&(a[b]=c[b])}};var Ma,Na,Oa,Pa,Qa,Ra=function(){return q.navigator?q.navigator.userAgent:n},Sa=function(){return q.navigator};Pa=Oa=Na=Ma=!1;var Ta;if(Ta=Ra()){var Ua=Sa();Ma=Ta.indexOf("Opera")==0;Na=!Ma&&Ta.indexOf("MSIE")!=-1;Oa=!Ma&&Ta.indexOf("WebKit")!=-1;Pa=!Ma&&!Oa&&Ua.product=="Gecko"}var Va=Ma,A=Na,B=Pa,C=Oa,Wa=Sa();Qa=(Wa&&Wa.platform||"").indexOf("Mac")!=-1;var Xa=!!Sa()&&(Sa().appVersion||"").indexOf("X11")!=-1,Ya;
a:{var Za="",$a;if(Va&&q.opera)var ab=q.opera.version,Za=typeof ab=="function"?ab():ab;else if(B?$a=/rv\:([^\);]+)(\)|;)/:A?$a=/MSIE\s+([^\);]+)(\)|;)/:C&&($a=/WebKit\/(\S+)/),$a)var bb=$a.exec(Ra()),Za=bb?bb[1]:"";if(A){var cb,db=q.document;cb=db?db.documentMode:i;if(cb>parseFloat(Za)){Ya=String(cb);break a}}Ya=Za}var eb=Ya,fb={},D=function(a){return fb[a]||(fb[a]=ua(eb,a)>=0)};var gb,hb=!A||D("9");!B&&!A||A&&D("9")||B&&D("1.9.1");var ib=A&&!D("9");var jb=function(a){return(a=a.className)&&typeof a.split=="function"?a.split(/\s+/):[]},kb=function(a){var b=jb(a),c=Da(arguments,1),d;d=b;for(var e=0,f=0;f<c.length;f++)z(d,c[f])>=0||(d.push(c[f]),e++);d=e==c.length;a.className=b.join(" ");return d},lb=function(a){for(var b=jb(a),c=Da(arguments,1),d=b,e=0,f=0;f<d.length;f++)z(c,d[f])>=0&&(Ea(d,f--,1),e++);a.className=b.join(" ")};var nb=function(a){return a?new mb(F(a)):gb||(gb=new mb)},G=function(a){return s(a)?document.getElementById(a):a},ob=function(a,b,c){c=c||document;a=a&&a!="*"?a.toUpperCase():"";if(c.querySelectorAll&&c.querySelector&&(!C||document.compatMode=="CSS1Compat"||D("528"))&&(a||b))return c.querySelectorAll(a+(b?"."+b:""));if(b&&c.getElementsByClassName)if(c=c.getElementsByClassName(b),a){for(var d={},e=0,f=0,g;g=c[f];f++)a==g.nodeName&&(d[e++]=g);d.length=e;return d}else return c;c=c.getElementsByTagName(a||
"*");if(b){d={};for(f=e=0;g=c[f];f++)a=g.className,typeof a.split=="function"&&z(a.split(/\s+/),b)>=0&&(d[e++]=g);d.length=e;return d}else return c},pb=function(a,b){return ob("LI",a,b)},rb=function(a,b){Ha(b,function(b,d){d=="style"?a.style.cssText=b:d=="class"?a.className=b:d=="for"?a.htmlFor=b:d in qb?a.setAttribute(qb[d],b):a[d]=b})},qb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",
maxlength:"maxLength",type:"type"},H=function(){return sb(document,arguments)},sb=function(a,b){var c=b[0],d=b[1];if(!hb&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',ra(d.name),'"');if(d.type){c.push(' type="',ra(d.type),'"');var e={};La(e,d);d=e;delete d.type}c.push(">");c=c.join("")}c=a.createElement(c);if(d)s(d)?c.className=d:r(d)?kb.apply(n,[c].concat(d)):rb(c,d);b.length>2&&tb(a,c,b);return c},tb=function(a,b,c){function d(c){c&&b.appendChild(s(c)?a.createTextNode(c):c)}for(var e=
2;e<c.length;e++){var f=c[e];if(ca(f)&&!(ea(f)&&f.nodeType>0)){var g;a:{if(f&&typeof f.length=="number")if(ea(f)){g=typeof f.item=="function"||typeof f.item=="string";break a}else if(da(f)){g=typeof f.item=="function";break a}g=!1}xa(g?Ca(f):f,d)}else d(f)}},ub=function(a,b){a.appendChild(b)},vb=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):n},F=function(a){return a.nodeType==9?a:a.ownerDocument||a.document},wb={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},xb={IMG:" ",BR:"\n"},zb=function(a){if(ib&&
"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];yb(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");A||(a=a.replace(/ +/g," "));a!=" "&&(a=a.replace(/^\s*/,""));return a},yb=function(a,b,c){if(!(a.nodeName in wb))if(a.nodeType==3)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in xb)b.push(xb[a.nodeName]);else for(a=a.firstChild;a;)yb(a,b,c),a=a.nextSibling},mb=function(a){this.w=
a||q.document||document};o=mb.prototype;o.Jb=nb;o.b=function(a){return s(a)?this.w.getElementById(a):a};o.W=function(){return sb(this.w,arguments)};o.createElement=function(a){return this.w.createElement(a)};o.createTextNode=function(a){return this.w.createTextNode(a)};o.appendChild=ub;o.pb=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};o.removeNode=vb;var Ab=new Function("a","return a");var Bb;!A||D("9");var Cb=A&&!D("8");var I=function(){};I.prototype.Pb=!1;I.prototype.k=function(){if(!this.Pb)this.Pb=!0,this.c()};I.prototype.c=function(){};var J=function(a,b){this.type=a;this.currentTarget=this.target=b};w(J,I);o=J.prototype;o.c=function(){delete this.type;delete this.target;delete this.currentTarget};o.V=!1;o.ka=!0;o.stopPropagation=function(){this.V=!0};o.preventDefault=function(){this.ka=!1};var Db=function(a,b){a&&this.U(a,b)};w(Db,J);o=Db.prototype;o.target=n;o.relatedTarget=n;o.offsetX=0;o.offsetY=0;o.clientX=0;o.clientY=0;o.screenX=0;o.screenY=0;o.button=0;o.keyCode=0;o.charCode=0;o.ctrlKey=!1;o.altKey=!1;o.shiftKey=!1;o.metaKey=!1;o.Jc=!1;o.R=n;
o.U=function(a,b){var c=this.type=a.type;J.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(B){var e;a:{try{Ab(d.nodeName);e=!0;break a}catch(f){}e=!1}e||(d=n)}}else if(c=="mouseover")d=a.fromElement;else if(c=="mouseout")d=a.toElement;this.relatedTarget=d;this.offsetX=a.offsetX!==i?a.offsetX:a.layerX;this.offsetY=a.offsetY!==i?a.offsetY:a.layerY;this.clientX=a.clientX!==i?a.clientX:a.pageX;this.clientY=a.clientY!==i?a.clientY:a.pageY;this.screenX=
a.screenX||0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||(c=="keypress"?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.Jc=Qa?a.metaKey:a.ctrlKey;this.state=a.state;this.R=a;delete this.ka;delete this.V};o.stopPropagation=function(){Db.d.stopPropagation.call(this);this.R.stopPropagation?this.R.stopPropagation():this.R.cancelBubble=!0};
o.preventDefault=function(){Db.d.preventDefault.call(this);var a=this.R;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Cb)try{if(a.ctrlKey||a.keyCode>=112&&a.keyCode<=123)a.keyCode=-1}catch(b){}};o.c=function(){Db.d.c.call(this);this.relatedTarget=this.currentTarget=this.target=this.R=n};var K=function(a,b){this.Rb=b;this.T=[];a>this.Rb&&h(Error("[goog.structs.SimplePool] Initial cannot be greater than max"));for(var c=0;c<a;c++)this.T.push(this.F?this.F():{})};w(K,I);K.prototype.F=n;K.prototype.Sb=n;K.prototype.getObject=function(){if(this.T.length)return this.T.pop();return this.F?this.F():{}};var Fb=function(a,b){a.T.length<a.Rb?a.T.push(b):Eb(a,b)},Eb=function(a,b){if(a.Sb)a.Sb(b);else if(ea(b))if(da(b.k))b.k();else for(var c in b)delete b[c]};
K.prototype.c=function(){K.d.c.call(this);for(var a=this.T;a.length;)Eb(this,a.pop());delete this.T};var Gb,Hb=(Gb="ScriptEngine"in q&&q.ScriptEngine()=="JScript")?q.ScriptEngineMajorVersion()+"."+q.ScriptEngineMinorVersion()+"."+q.ScriptEngineBuildVersion():"0";var Ib=function(){},Jb=0;o=Ib.prototype;o.key=0;o.$=!1;o.cb=!1;o.U=function(a,b,c,d,e,f){da(a)?this.Ob=!0:a&&a.handleEvent&&da(a.handleEvent)?this.Ob=!1:h(Error("Invalid listener argument"));this.Z=a;this.Hb=b;this.src=c;this.type=d;this.capture=!!e;this.wa=f;this.cb=!1;this.key=++Jb;this.$=!1};o.handleEvent=function(a){if(this.Ob)return this.Z.call(this.wa||this.src,a);return this.Z.handleEvent.call(this.Z,a)};var Kb,Lb,Mb,Nb,Ob,Pb,Qb,Rb,Sb,Tb,Ub;
(function(){function a(){return{A:0,s:0}}function b(){return[]}function c(){var a=function(b){return g.call(a.src,a.key,b)};return a}function d(){return new Ib}function e(){return new Db}var f=Gb&&!(ua(Hb,"5.7")>=0),g;Pb=function(a){g=a};if(f){Kb=function(){return j.getObject()};Lb=function(a){Fb(j,a)};Mb=function(){return k.getObject()};Nb=function(a){Fb(k,a)};Ob=function(){return l.getObject()};Qb=function(){Fb(l,c())};Rb=function(){return v.getObject()};Sb=function(a){Fb(v,a)};Tb=function(){return m.getObject()};
Ub=function(a){Fb(m,a)};var j=new K(0,600);j.F=a;var k=new K(0,600);k.F=b;var l=new K(0,600);l.F=c;var v=new K(0,600);v.F=d;var m=new K(0,600);m.F=e}else Kb=a,Lb=aa,Mb=b,Nb=aa,Ob=c,Qb=aa,Rb=d,Sb=aa,Tb=e,Ub=aa})();var Vb={},L={},M={},Wb={},N=function(a,b,c,d,e){if(b)if(r(b)){for(var f=0;f<b.length;f++)N(a,b[f],c,d,e);return n}else{var d=!!d,g=L;b in g||(g[b]=Kb());g=g[b];d in g||(g[d]=Kb(),g.A++);var g=g[d],j=ha(a),k;g.s++;if(g[j]){k=g[j];for(f=0;f<k.length;f++)if(g=k[f],g.Z==c&&g.wa==e){if(g.$)break;return k[f].key}}else k=g[j]=Mb(),g.A++;f=Ob();f.src=a;g=Rb();g.U(c,f,a,b,d,e);c=g.key;f.key=c;k.push(g);Vb[c]=g;M[j]||(M[j]=Mb());M[j].push(g);a.addEventListener?(a==q||!a.Gb)&&a.addEventListener(b,f,d):a.attachEvent(Xb(b),
f);return c}else h(Error("Invalid event type"))},Yb=function(a,b,c,d,e){if(r(b)){for(var f=0;f<b.length;f++)Yb(a,b[f],c,d,e);return n}a=N(a,b,c,d,e);Vb[a].cb=!0;return a},Zb=function(a,b,c,d,e){if(r(b))for(var f=0;f<b.length;f++)Zb(a,b[f],c,d,e);else if(d=!!d,a=$b(a,b,d))for(f=0;f<a.length;f++)if(a[f].Z==c&&a[f].capture==d&&a[f].wa==e){O(a[f].key);break}},O=function(a){if(Vb[a]){var b=Vb[a];if(!b.$){var c=b.src,d=b.type,e=b.Hb,f=b.capture;c.removeEventListener?(c==q||!c.Gb)&&c.removeEventListener(d,
e,f):c.detachEvent&&c.detachEvent(Xb(d),e);c=ha(c);e=L[d][f][c];if(M[c]){var g=M[c],j=z(g,b);j>=0&&(x(g.length!=n),y.splice.call(g,j,1));g.length==0&&delete M[c]}b.$=!0;e.Nb=!0;ac(d,f,c,e);delete Vb[a]}}},ac=function(a,b,c,d){if(!d.Ea&&d.Nb){for(var e=0,f=0;e<d.length;e++)if(d[e].$){var g=d[e].Hb;g.src=n;Qb(g);Sb(d[e])}else e!=f&&(d[f]=d[e]),f++;d.length=f;d.Nb=!1;f==0&&(Nb(d),delete L[a][b][c],L[a][b].A--,L[a][b].A==0&&(Lb(L[a][b]),delete L[a][b],L[a].A--),L[a].A==0&&(Lb(L[a]),delete L[a]))}},bc=
function(a){var b,c=0,d=b==n;b=!!b;if(a==n)Ha(M,function(a){for(var f=a.length-1;f>=0;f--){var e=a[f];if(d||b==e.capture)O(e.key),c++}});else if(a=ha(a),M[a])for(var a=M[a],e=a.length-1;e>=0;e--){var f=a[e];if(d||b==f.capture)O(f.key),c++}},$b=function(a,b,c){var d=L;if(b in d&&(d=d[b],c in d&&(d=d[c],a=ha(a),d[a])))return d[a];return n},Xb=function(a){if(a in Wb)return Wb[a];return Wb[a]="on"+a},dc=function(a,b,c,d,e){var f=1,b=ha(b);if(a[b]){a.s--;a=a[b];a.Ea?a.Ea++:a.Ea=1;try{for(var g=a.length,
j=0;j<g;j++){var k=a[j];k&&!k.$&&(f&=cc(k,e)!==!1)}}finally{a.Ea--,ac(c,d,b,a)}}return Boolean(f)},cc=function(a,b){var c=a.handleEvent(b);a.cb&&O(a.key);return c};
Pb(function(a,b){if(!Vb[a])return!0;var c=Vb[a],d=c.type,e=L;if(!(d in e))return!0;var e=e[d],f,g;Bb===i&&(Bb=A&&!q.addEventListener);if(Bb){var j;if(!(j=b))a:{j="window.event".split(".");for(var k=q;f=j.shift();)if(k[f]!=n)k=k[f];else{j=n;break a}j=k}f=j;j=!0 in e;k=!1 in e;if(j){if(f.keyCode<0||f.returnValue!=i)return!0;a:{var l=!1;if(f.keyCode==0)try{f.keyCode=-1;break a}catch(v){l=!0}if(l||f.returnValue==i)f.returnValue=!0}}l=Tb();l.U(f,this);f=!0;try{if(j){for(var m=Mb(),p=l.currentTarget;p;p=
p.parentNode)m.push(p);g=e[!0];g.s=g.A;for(var E=m.length-1;!l.V&&E>=0&&g.s;E--)l.currentTarget=m[E],f&=dc(g,m[E],d,!0,l);if(k){g=e[!1];g.s=g.A;for(E=0;!l.V&&E<m.length&&g.s;E++)l.currentTarget=m[E],f&=dc(g,m[E],d,!1,l)}}else f=cc(c,l)}finally{if(m)m.length=0,Nb(m);l.k();Ub(l)}return f}d=new Db(b,this);try{f=cc(c,d)}finally{d.k()}return f});var ec="StopIteration"in q?q.StopIteration:Error("StopIteration"),fc=function(){};fc.prototype.next=function(){h(ec)};fc.prototype.Ub=function(){return this};
var gc=function(a){if(a instanceof fc)return a;if(typeof a.Ub=="function")return a.Ub(!1);if(ca(a)){var b=0,c=new fc;c.next=function(){for(;;)if(b>=a.length&&h(ec),b in a)return a[b++];else b++};return c}h(Error("Not implemented"))},hc=function(a,b,c){if(ca(a))try{xa(a,b,c)}catch(d){d!==ec&&h(d)}else{a=gc(a);try{for(;;)b.call(c,a.next(),i,a)}catch(e){e!==ec&&h(e)}}},ic=function(a,b){a=gc(a);try{for(;;)if(b.call(i,a.next(),i,a))break}catch(c){c!==ec&&h(c)}};var P=function(){};w(P,I);o=P.prototype;o.Gb=!0;o.va=n;o.Pa=function(a){this.va=a};o.addEventListener=function(a,b,c,d){N(this,a,b,c,d)};o.removeEventListener=function(a,b,c,d){Zb(this,a,b,c,d)};
o.dispatchEvent=function(a){var b=a.type||a,c=L;if(b in c){if(s(a))a=new J(a,this);else if(a instanceof J)a.target=a.target||this;else{var d=a,a=new J(b,this);La(a,d)}var d=1,e,c=c[b],b=!0 in c,f;if(b){e=[];for(f=this;f;f=f.va)e.push(f);f=c[!0];f.s=f.A;for(var g=e.length-1;!a.V&&g>=0&&f.s;g--)a.currentTarget=e[g],d&=dc(f,e[g],a.type,!0,a)&&a.ka!=!1}if(!1 in c)if(f=c[!1],f.s=f.A,b)for(g=0;!a.V&&g<e.length&&f.s;g++)a.currentTarget=e[g],d&=dc(f,e[g],a.type,!1,a)&&a.ka!=!1;else for(e=this;!a.V&&e&&f.s;e=
e.va)a.currentTarget=e,d&=dc(f,e,a.type,!1,a)&&a.ka!=!1;a=Boolean(d)}else a=!0;return a};o.c=function(){P.d.c.call(this);bc(this);this.va=n};var kc=function(a,b){this.Da=a||1;this.ja=b||jc;this.Za=t(this.Mc,this);this.$a=u()};w(kc,P);kc.prototype.enabled=!1;var jc=q.window;o=kc.prototype;o.i=n;o.Mc=function(){if(this.enabled){var a=u()-this.$a;if(a>0&&a<this.Da*0.8)this.i=this.ja.setTimeout(this.Za,this.Da-a);else if(this.dispatchEvent("tick"),this.enabled)this.i=this.ja.setTimeout(this.Za,this.Da),this.$a=u()}};o.start=function(){this.enabled=!0;if(!this.i)this.i=this.ja.setTimeout(this.Za,this.Da),this.$a=u()};
o.stop=function(){this.enabled=!1;if(this.i)this.ja.clearTimeout(this.i),this.i=n};o.c=function(){kc.d.c.call(this);this.stop();delete this.ja};var lc=function(a,b){da(a)?b&&(a=t(a,b)):a&&typeof a.handleEvent=="function"?a=t(a.handleEvent,a):h(Error("Invalid listener argument"));jc.setTimeout(a,10)};var Q=function(a,b,c,d){(!r(a)||!r(b))&&h(Error("Start and end parameters must be arrays"));a.length!=b.length&&h(Error("Start and end points must be the same length"));this.la=a;this.Oc=b;this.duration=c;this.Tb=d;this.coords=[]};w(Q,P);var Ia={},mc=n,oc=function(){jc.clearTimeout(mc);var a=u(),b;for(b in Ia)nc(Ia[b],a);mc=Ja()?n:jc.setTimeout(oc,20)},pc=function(a){a=ha(a);delete Ia[a];mc&&Ja()&&(jc.clearTimeout(mc),mc=n)};o=Q.prototype;o.z=0;o.Ib=0;o.o=0;o.startTime=n;o.Fb=n;o.Xa=n;
o.play=function(a){if(a||this.z==0)this.o=0,this.coords=this.la;else if(this.z==1)return!1;pc(this);this.startTime=u();this.z==-1&&(this.startTime-=this.duration*this.o);this.Fb=this.startTime+this.duration;this.Xa=this.startTime;this.o||this.S();qc(this,"play");this.z==-1&&qc(this,"resume");this.z=1;a=ha(this);a in Ia||(Ia[a]=this);mc||(mc=jc.setTimeout(oc,20));nc(this,this.startTime);return!0};o.stop=function(a){pc(this);this.z=0;if(a)this.o=1;rc(this,this.o);qc(this,"stop");this.aa()};
o.c=function(){this.z!=0&&this.stop(!1);qc(this,"destroy");Q.d.c.call(this)};var nc=function(a,b){a.o=(b-a.startTime)/(a.Fb-a.startTime);if(a.o>=1)a.o=1;a.Ib=1E3/(b-a.Xa);a.Xa=b;rc(a,a.o);a.o==1?(a.z=0,pc(a),qc(a,"finish"),a.aa()):a.z==1&&a.Wa()},rc=function(a,b){da(a.Tb)&&(b=a.Tb(b));a.coords=Array(a.la.length);for(var c=0;c<a.la.length;c++)a.coords[c]=(a.Oc[c]-a.la[c])*b+a.la[c]};Q.prototype.Wa=function(){qc(this,"animate")};Q.prototype.S=function(){qc(this,"begin")};
Q.prototype.aa=function(){qc(this,"end")};var qc=function(a,b){a.dispatchEvent(new sc(b,a))},sc=function(a,b){J.call(this,a);this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.Xc=b.coords[2];this.duration=b.duration;this.o=b.o;this.Wc=b.Ib;this.state=b.z;this.Vc=b};w(sc,J);var uc=function(a,b,c,d,e){if(!A&&(!C||!D("525")))return!0;if(Qa&&e)return tc(a);if(e&&!d)return!1;if(!c&&(b==17||b==18))return!1;if(A&&d&&b==a)return!1;switch(a){case 13:return!0;case 27:return!C}return tc(a)},tc=function(a){if(a>=48&&a<=57)return!0;if(a>=96&&a<=106)return!0;if(a>=65&&a<=90)return!0;if(C&&a==0)return!0;switch(a){case 32:case 63:case 107:case 109:case 110:case 111:case 186:case 189:case 187:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:return!0;default:return!1}};var vc=function(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d};vc.prototype.toString=function(){return"("+this.top+"t, "+this.right+"r, "+this.bottom+"b, "+this.left+"l)"};var wc=function(a,b){var c=F(a);if(c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,n)))return c[b]||c.getPropertyValue(b);return""},xc=function(a,b){return wc(a,b)||(a.currentStyle?a.currentStyle[b]:n)||a.style[b]},yc=function(a){var a=a?a.nodeType==9?a:F(a):document,b;if(b=A)if(b=!D(9))b=nb(a).w.compatMode!="CSS1Compat";if(b)return a.body;return a.documentElement},zc=function(a){if(A)return a.offsetParent;for(var b=F(a),c=xc(a,"position"),d=c=="fixed"||c=="absolute",
a=a.parentNode;a&&a!=b;a=a.parentNode)if(c=xc(a,"position"),d=d&&c=="static"&&a!=b.documentElement&&a!=b.body,!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||c=="fixed"||c=="absolute"||c=="relative"))return a;return n},Ac=function(a){var b,c=F(a),d=xc(a,"position"),e=B&&c.getBoxObjectFor&&!a.getBoundingClientRect&&d=="absolute"&&(b=c.getBoxObjectFor(a))&&(b.screenX<0||b.screenY<0),f=new Fa(0,0),g=yc(c);if(a==g)return f;if(a.getBoundingClientRect){b=a.getBoundingClientRect();if(A)a=
a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop;a=nb(c).w;c=!C&&a.compatMode=="CSS1Compat"?a.documentElement:a.body;a=a.parentWindow||a.defaultView;c=new Fa(a.pageXOffset||c.scrollLeft,a.pageYOffset||c.scrollTop);f.x=b.left+c.x;f.y=b.top+c.y}else if(c.getBoxObjectFor&&!e)b=c.getBoxObjectFor(a),c=c.getBoxObjectFor(g),f.x=b.screenX-c.screenX,f.y=b.screenY-c.screenY;else{b=a;do{f.x+=b.offsetLeft;f.y+=b.offsetTop;b!=a&&(f.x+=b.clientLeft||
0,f.y+=b.clientTop||0);if(C&&xc(b,"position")=="fixed"){f.x+=c.body.scrollLeft;f.y+=c.body.scrollTop;break}b=b.offsetParent}while(b&&b!=a);if(Va||C&&d=="absolute")f.y-=c.body.offsetTop;for(b=a;(b=zc(b))&&b!=c.body&&b!=g;)if(f.x-=b.scrollLeft,!Va||b.tagName!="TR")f.y-=b.scrollTop}return f},Bc=function(a,b){typeof a=="number"&&(a=(b?Math.round(a):a)+"px");return a},Cc=function(a){if(xc(a,"display")!="none")return new Ga(a.offsetWidth,a.offsetHeight);var b=a.style,c=b.display,d=b.visibility,e=b.position;
b.visibility="hidden";b.position="absolute";b.display="inline";var f=a.offsetWidth,a=a.offsetHeight;b.display=c;b.position=e;b.visibility=d;return new Ga(f,a)},Dc=function(a,b){a.style.display=b?"":"none"},Ec=B?"MozUserSelect":C?"WebkitUserSelect":n,Fc=function(a){var b=a.getElementsByTagName("*");if(Ec){var c="none";a.style[Ec]=c;if(b)for(var a=0,d;d=b[a];a++)d.style[Ec]=c}else if(A||Va)if(c="on",a.setAttribute("unselectable",c),b)for(a=0;d=b[a];a++)d.setAttribute("unselectable",c)},Gc={thin:2,medium:4,
thick:6},Hc=function(a,b){if((a.currentStyle?a.currentStyle[b+"Style"]:n)=="none")return 0;var c=a.currentStyle?a.currentStyle[b+"Width"]:n;if(c in Gc)return Gc[c];var d;if(/^\d+px?$/.test(c))d=parseInt(c,10);else{d=a.style.left;var e=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=c;c=a.style.pixelLeft;a.style.left=d;a.runtimeStyle.left=e;d=c}return d};var R=function(a,b,c,d,e){function f(a){if(a)a.tabIndex=0,N(a,"click",g.ic,!1,g),N(a,"keydown",g.jc,!1,g)}this.e=e||nb();this.P=this.e.b(a)||n;this.ga=this.e.b(d||n);this.ta=(this.Ta=da(b)?b:n)||!b?n:this.e.b(b);this.D=c==!0;var g=this;f(this.P);f(this.ga);this.ia(this.D)};w(R,P);R.prototype.c=function(){this.P&&bc(this.P);this.ga&&bc(this.ga);R.d.c.call(this)};R.prototype.ma=function(){return this.ta};R.prototype.collapse=function(){this.ia(!1)};
R.prototype.ia=function(a){if(this.ta)Dc(this.ta,a);else if(a&&this.Ta)this.ta=this.Ta();this.ga?(Dc(this.P,!a),Dc(this.ga,a)):Ic(this,a);this.D=a;this.dispatchEvent(new Jc("toggle",this,this.D))};var Ic=function(a,b){if(a.P){var c=a.P;b?kb(c,"goog-zippy-expanded"):lb(c,"goog-zippy-expanded");c=a.P;!b?kb(c,"goog-zippy-collapsed"):lb(c,"goog-zippy-collapsed")}};R.prototype.jc=function(a){if(a.keyCode==13||a.keyCode==32)this.ia(!this.D),a.preventDefault(),a.stopPropagation()};R.prototype.ic=function(){this.ia(!this.D)};
var Jc=function(a,b,c){J.call(this,a,b);this.Yc=c};w(Jc,J);var Kc=function(a,b,c){var d=H("div",{style:"overflow:hidden"}),b=G(b);b.parentNode.replaceChild(d,b);d.appendChild(b);this.Ca=d;this.B=n;R.call(this,a,b,c);a=this.D;this.Ca.style.display=a?"":"none";Ic(this,a)};w(Kc,R);o=Kc.prototype;o.yc=500;o.xc=function(a){return 1-Math.pow(1-a,3)};
o.ia=function(a){if(this.D!=a||this.B){if(this.Ca.style.display=="none")this.Ca.style.display="";var b=this.ma().offsetHeight,c=0;this.B?(a=this.D,bc(this.B),this.B.stop(!1),c=b-Math.abs(parseInt(this.ma().style.marginTop,10))):c=a?0:b;Ic(this,a);this.B=new Q([0,c],[0,a?b:0],this.yc,this.xc);N(this.B,["begin","animate","end"],this.Bc,!1,this);N(this.B,"end",t(this.Cc,this,a));this.B.play(!1)}};o.Bc=function(a){var b=this.ma();b.style.marginTop=a.y-b.offsetHeight+"px"};
o.Cc=function(a){if(a)this.ma().style.marginTop="0";bc(this.B);this.D=a;this.B=n;if(!a)this.Ca.style.display="none";this.dispatchEvent(new Jc("toggle",this,a))};var Lc=function(a){this.bb=a};w(Lc,I);
var Mc=new K(0,100),Nc=[],S=function(a,b,c,d){r(c)||(Nc[0]=c,c=Nc);for(var e=0;e<c.length;e++)Oc(a,N(b,c[e],d||a,!1,a.bb||a))},Pc=function(a,b,c,d,e,f){if(r(c))for(var g=0;g<c.length;g++)Pc(a,b,c[g],d,e,f);else Oc(a,Yb(b,c,d||a,e||!1,f||a.bb||a))},Oc=function(a,b){a.p?a.p[b]=!0:a.N?(a.p=Mc.getObject(),a.p[a.N]=!0,a.N=n,a.p[b]=!0):a.N=b},Qc=function(a,b,c,d,e,f){if(a.N||a.p)if(r(c))for(var g=0;g<c.length;g++)Qc(a,b,c[g],d,e,f);else{a:{d=d||a;f=f||a.bb||a;e=!!e;if(b=$b(b,c,e))for(c=0;c<b.length;c++)if(b[c].Z==
d&&b[c].capture==e&&b[c].wa==f){b=b[c];break a}b=n}if(b)if(b=b.key,O(b),a.p)a=a.p,b in a&&delete a[b];else if(a.N==b)a.N=n}},Rc=function(a){if(a.p){for(var b in a.p)O(b),delete a.p[b];Fb(Mc,a.p);a.p=n}else a.N&&O(a.N)};Lc.prototype.c=function(){Lc.d.c.call(this);Rc(this)};Lc.prototype.handleEvent=function(){h(Error("EventHandler.handleEvent not implemented"))};var Sc=function(){};(function(a){a.oa=function(){return a.Pc||(a.Pc=new a)}})(Sc);Sc.prototype.Tc=0;var Tc=function(a){return":"+(a.Tc++).toString(36)};Sc.oa();var T=function(a){this.e=a||nb();this.Kc=Uc};w(T,P);T.prototype.ec=Sc.oa();var Uc=n;o=T.prototype;o.yb=n;o.G=!1;o.a=n;o.Kc=n;o.$b=n;o.u=n;o.H=n;o.ra=n;o.fb=!1;o.b=function(){return this.a};o.Pa=function(a){this.u&&this.u!=a&&h(Error("Method not supported"));T.d.Pa.call(this,a)};o.Jb=function(){return this.e};o.W=function(){this.a=this.e.createElement("div")};
o.qb=function(a){this.G&&h(Error("Component already rendered"));this.a||this.W();a?a.insertBefore(this.a,n):this.e.w.body.appendChild(this.a);(!this.u||this.u.G)&&this.ea()};var Vc=function(a,b){if(a.G)h(Error("Component already rendered"));else if(b){a.fb=!0;if(!a.e||a.e.w!=F(b))a.e=nb(b);a.Ua(b);a.ea()}else h(Error("Invalid element to decorate"))};o=T.prototype;o.Ua=function(a){this.a=a};o.ea=function(){this.G=!0;Wc(this,function(a){!a.G&&a.b()&&a.ea()})};
o.ca=function(){Wc(this,function(a){a.G&&a.ca()});this.sa&&Rc(this.sa);this.G=!1};o.c=function(){T.d.c.call(this);this.G&&this.ca();this.sa&&(this.sa.k(),delete this.sa);Wc(this,function(a){a.k()});!this.fb&&this.a&&vb(this.a);this.u=this.$b=this.a=this.ra=this.H=n};o.ma=function(){return this.a};var Wc=function(a,b){a.H&&xa(a.H,b,i)};
T.prototype.removeChild=function(a,b){if(a){var c=s(a)?a:a.yb||(a.yb=Tc(a.ec)),d;this.ra&&c?(d=this.ra,d=c in d?d[c]:i,d=d||n):d=n;a=d;if(c&&a)d=this.ra,c in d&&delete d[c],c=this.H,d=z(c,a),d>=0&&(x(c.length!=n),y.splice.call(c,d,1)),b&&(a.ca(),a.a&&vb(a.a)),c=a,c==n&&h(Error("Unable to set parent component")),c.u=n,T.d.Pa.call(c,n)}a||h(Error("Child is not in parent component"));return a};T.prototype.pb=function(a){for(;this.H&&this.H.length!=0;)this.removeChild(this.H?this.H[0]||n:n,a)};var U=function(a,b){T.call(this,b);this.Y=a||""};w(U,T);o=U.prototype;o.M=n;o.xa=!1;o.W=function(){this.a=this.Jb().W("input",{type:"text"})};o.Ua=function(a){U.d.Ua.call(this,a);if(!this.Y)this.Y=a.getAttribute("label")||""};
o.ea=function(){U.d.ea.call(this);var a=new Lc(this);S(a,this.b(),"focus",this.La);S(a,this.b(),"blur",this.mc);B&&S(a,this.b(),["keypress","keydown","keyup"],this.nc);S(a,F(this.b())?F(this.b()).parentWindow||F(this.b()).defaultView:window,"load",this.oc);this.J=a;Xc(this);Yc(this);this.b().kc=this};o.ca=function(){U.d.ca.call(this);Zc(this);this.b().kc=n};var Xc=function(a){if(!a.vc&&a.J&&a.b().form)S(a.J,a.b().form,"submit",a.wc),a.vc=!0},Zc=function(a){if(a.J)a.J.k(),a.J=n};o=U.prototype;
o.c=function(){U.d.c.call(this);Zc(this)};o.Ya="label-input-label";o.La=function(){this.xa=!0;lb(this.b(),this.Ya);if(!$c(this)&&!this.Ra){var a=this,b=function(){a.b().value=""};A?lc(b):b()}};o.mc=function(){Qc(this.J,this.b(),"click",this.La);this.M=n;this.xa=!1;Yc(this)};o.nc=function(a){if(a.keyCode==27){if(a.type=="keydown")this.M=this.b().value;else if(a.type=="keypress")this.b().value=this.M;else if(a.type=="keyup")this.M=n;a.preventDefault()}};
o.wc=function(){if(!$c(this))this.b().value="",lc(this.Hc,this)};o.Hc=function(){if(!$c(this))this.b().value=this.Y};o.oc=function(){Yc(this)};var $c=function(a){return a.b().value!=""&&a.b().value!=a.Y};U.prototype.Ma=function(a){if(this.M!=n)this.M=a;this.b().value=a;Yc(this)};U.prototype.O=function(){if(this.M!=n)return this.M;return $c(this)?this.b().value:""};var Yc=function(a){Xc(a);$c(a)?lb(a.b(),a.Ya):(!a.Ra&&!a.xa&&kb(a.b(),a.Ya),lc(a.sc,a))};U.prototype.lc=function(){this.Ra=!1};
U.prototype.sc=function(){if(this.b()&&!$c(this)&&!this.xa)this.b().value=this.Y};var V=function(a,b,c){this.eb=a;this.Ha=c;this.v=b;N(b,["hilite","select","canceldismiss","dismiss"],this);this.q=n;this.h=[];this.m=-1;this.n=0;this.Q=this.j=n};w(V,P);o=V.prototype;o.Ab=10;o.fc=!0;o.Db=!1;o.Eb=!1;o.Cb=!1;o.handleEvent=function(a){if(a.target==this.v)switch(a.type){case "hilite":this.r(a.ua);break;case "select":ad(this);break;case "canceldismiss":bd(this);break;case "dismiss":cd(this)}};
var dd=function(a){var b=a.n+a.h.length-1;a.m>=a.n&&a.m<b?a.r(a.m+1):a.m==-1?a.r(a.n):a.m==b&&(a.Db?a.r(-1):a.Eb&&a.r(a.n))},ed=function(a){a.m>a.n?a.r(a.m-1):a.Db&&a.m==a.n?a.r(-1):a.Eb&&(a.m==-1||a.m==a.n)&&a.r(a.n+a.h.length-1)};V.prototype.r=function(a){this.m=a;this.v.r(a);return fd(this,a)!=-1};
var ad=function(a){var b=fd(a,a.m);if(b!=-1){var b=a.h[b],c=a.Ha.Qa(b);a.Cb?(a.q=n,cd(a)):a.C();c||(a.dispatchEvent({type:"update",ua:b}),a.Cb&&a.Ha.update(!0));return!0}else return a.C(),a.dispatchEvent({type:"update",ua:n}),!1};V.prototype.C=function(){this.m=-1;this.q=n;this.n+=this.h.length;this.h=[];window.clearTimeout(this.Q);this.Q=n;this.v.C()};
var cd=function(a){if(!a.Q)a.Q=window.setTimeout(t(a.C,a),100)},bd=function(a){window.setTimeout(t(function(){if(this.Q)window.clearTimeout(this.Q),this.Q=n},a),10)};V.prototype.c=function(){V.d.c.call(this);this.v.k();this.Ha.k();this.eb=n};V.prototype.hc=function(a,b,c){this.q==a&&this.Sa(b,c)};
V.prototype.Sa=function(a,b){var c=b?fd(this,this.m):n;this.n+=this.h.length;this.h=a;for(var d=[],e=0;e<a.length;++e)d.push({id:this.n+e,data:a[e]});this.v.Sa(d,this.q,this.j);this.fc&&d.length!=0&&this.q?this.r(c!=n?this.n+c:this.n):this.m=-1;this.dispatchEvent("suggestionsupdate")};var fd=function(a,b){var c=b-a.n;if(c<0||c>=a.h.length)return-1;return c};var gd=function(a){this.h=a;this.bc=!1},hd=function(a,b,c){var d=[];if(b!=""){var b=sa(b),e=RegExp("(^|\\W+)"+b,"i");ic(a.h,function(a){String(a).match(e)&&d.push(a);return d.length>=c})}return d},id=function(a,b,c){var d=[];hc(a.h,function(a,c){var e=b.toLowerCase(),k=String(a).toLowerCase(),l=0;if(k.indexOf(e)!=-1)l=parseInt((k.indexOf(e)/4).toString(),10);else for(var v=e.split(""),m=-1,p=10,E=0,va;va=v[E];E++)va=k.indexOf(va),va>m?(m=va-m-1,m>p-5&&(m=p-5),l+=m,m=va):(l+=p,p+=5);l<e.length*6&&
d.push({Lc:a,Qb:l,index:c})});d.sort(function(a,b){var c=a.Qb-b.Qb;if(c!=0)return c;return a.index-b.index});for(var a=[],e=0;e<c&&e<d.length;e++)a.push(d[e].Lc);return a};var jd=function(a,b){a.setAttribute("role",b);a.$c=b};var md=function(a){var b;a:{var c=0,d=0;if(kd(a))c=a.selectionStart,d=-1;else if(A){var e=ld(a);b=e[0];e=e[1];if(b.inRange(e)){b.setEndPoint("EndToStart",e);if(a.type=="textarea"){e.duplicate();c=a=b.text;for(d=!1;!d;)b.compareEndPoints("StartToEnd",b)==0?d=!0:(b.moveEnd("character",-1),b.text==a?c+="\r\n":d=!0);b=[c.length,-1];break a}c=b.text.length;d=-1}}b=[c,d]}return b[0]},ld=function(a){var b=a.ownerDocument||a.document,c=b.selection.createRange();a.type=="textarea"?(b=b.body.createTextRange(),
b.moveToElementText(a)):b=a.createTextRange();return[b,c]},nd=function(a,b){if(a.type=="textarea")b=a.value.substring(0,b).replace(/(\r\n|\r|\n)/g,"\n").length;return b},kd=function(a){try{return typeof a.selectionStart=="number"}catch(b){return!1}};var W=function(a,b){a&&od(this,a,b)};w(W,P);o=W.prototype;o.a=n;o.ya=n;o.Va=n;o.za=n;o.L=-1;o.K=-1;
var pd={3:13,12:144,63232:38,63233:40,63234:37,63235:39,63236:112,63237:113,63238:114,63239:115,63240:116,63241:117,63242:118,63243:119,63244:120,63245:121,63246:122,63247:123,63248:44,63272:46,63273:36,63275:35,63276:33,63277:34,63289:144,63302:45},qd={Up:38,Down:40,Left:37,Right:39,Enter:13,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,"U+007F":46,Home:36,End:35,PageUp:33,PageDown:34,Insert:45},rd={61:187,59:186},sd=A||C&&D("525");
W.prototype.pc=function(a){if(C&&(this.L==17&&!a.ctrlKey||this.L==18&&!a.altKey))this.K=this.L=-1;sd&&!uc(a.keyCode,this.L,a.shiftKey,a.ctrlKey,a.altKey)?this.handleEvent(a):this.K=B&&a.keyCode in rd?rd[a.keyCode]:a.keyCode};W.prototype.qc=function(){this.K=this.L=-1};
W.prototype.handleEvent=function(a){var b=a.R,c,d;A&&a.type=="keypress"?(c=this.K,d=c!=13&&c!=27?b.keyCode:0):C&&a.type=="keypress"?(c=this.K,d=b.charCode>=0&&b.charCode<63232&&tc(c)?b.charCode:0):Va?(c=this.K,d=tc(c)?b.keyCode:0):(c=b.keyCode||this.K,d=b.charCode||0,Qa&&d==63&&!c&&(c=191));var e=c,f=b.keyIdentifier;c?c>=63232&&c in pd?e=pd[c]:c==25&&a.shiftKey&&(e=9):f&&f in qd&&(e=qd[f]);a=e==this.L;this.L=e;b=new td(e,d,a,b);try{this.dispatchEvent(b)}finally{b.k()}};W.prototype.b=function(){return this.a};
var od=function(a,b,c){a.za&&a.detach();a.a=b;a.ya=N(a.a,"keypress",a,c);a.Va=N(a.a,"keydown",a.pc,c,a);a.za=N(a.a,"keyup",a.qc,c,a)};W.prototype.detach=function(){if(this.ya)O(this.ya),O(this.Va),O(this.za),this.za=this.Va=this.ya=n;this.a=n;this.K=this.L=-1};W.prototype.c=function(){W.d.c.call(this);this.detach()};var td=function(a,b,c,d){d&&this.U(d,i);this.type="key";this.keyCode=a;this.charCode=b;this.repeat=c};w(td,Db);var X=function(a,b,c,d){d=d||150;this.ha=a!=n?a:",;";this.cc=this.ha.substring(0,1);a=this.X?"[\\s"+this.ha+"]+":"[\\s]+";this.nb=RegExp("^"+a+"|"+a+"$","g");this.dc=RegExp("\\s*["+this.ha+"]$");this.Bb=b||"";this.Zb=this.X=c!=n?c:!0;this.i=d>0?new kc(d):n;this.l=new Lc(this);this.Fa=new Lc(this);this.ba=new W;this.zb=-1};w(X,I);o=X.prototype;o.rc=!0;o.Nc=!0;o.tb=!1;o.Ec=!0;o.Dc=!0;o.g=n;o.Ka="";o.I=!1;o.Na=!1;o.ac=!0;o.O=function(){return this.g.value};o.Ma=function(a){this.g.value=a};
var ud=function(a,b){b.setAttribute("aria-haspopup",!0);S(a.l,b,"focus",a.Kb);S(a.l,b,"blur",a.tc);a.g||S(a.Fa,b,"keydown",a.uc)};
X.prototype.Qa=function(a,b){var c=a.toString();if(b!==i?b:this.X){var d=vd(this,this.O(),md(this.g)),e=wd(this,this.O());this.dc.test(c)||(c=c.replace(/[\s\xa0]+$/,"")+this.cc);this.rc&&(d!=0&&!/^[\s\xa0]*$/.test(e[d-1])&&(c=" "+c),d==e.length-1&&(c+=" "));if(c!=e[d]){e[d]=c;c=this.g;B&&c.blur();c.value=e.join("");for(var f=0,g=0;g<=d;g++)f+=e[g].length;c.focus();d=f;e=this.g;c=d;kd(e)?e.selectionStart=c:A&&(f=ld(e),g=f[0],g.inRange(f[1])&&(c=nd(e,c),g.collapse(!0),g.move("character",c),g.select()));
e=this.g;kd(e)?e.selectionEnd=d:A&&(f=ld(e),c=f[1],f[0].inRange(c)&&(d=nd(e,d),e=nd(e,md(e)),c.collapse(!0),c.moveEnd("character",d-e),c.select()))}}else this.Ma(c);this.Na=!0;return!1};X.prototype.c=function(){X.d.c.call(this);this.l.k();delete this.l;this.Fa.k();this.ba.k()};
var yd=function(a,b){switch(b.keyCode){case 40:if(a.f.v.t){a.tb?ed(a.f):dd(a.f);b.preventDefault();return}else if(!a.X){a.update(!0);b.preventDefault();return}break;case 38:if(a.f.v.t){a.tb?dd(a.f):ed(a.f);b.preventDefault();return}break;case 9:if(a.f.v.t&&!b.shiftKey){if(a.update(),ad(a.f)&&a.Zb){b.preventDefault();return}}else a.f.C();break;case 13:if(a.f.v.t){if(a.update(),ad(a.f)){b.preventDefault();b.stopPropagation();return}}else a.f.C();break;case 27:if(a.f.v.t){a.f.C();b.preventDefault();
b.stopPropagation();return}break;case 229:if(!a.I){if(!a.I)S(a.l,a.g,"keyup",a.sb),S(a.l,a.g,"keypress",a.rb),a.I=!0;return}break;default:a.i&&!a.ac&&(a.i.stop(),a.i.start())}xd(a,b)},xd=function(a,b){var c=a.X&&b.charCode&&a.ha.indexOf(String.fromCharCode(b.charCode))!=-1;a.Ec&&c&&a.update();a.Dc&&c&&ad(a.f)&&b.preventDefault()};o=X.prototype;o.gc=function(){return!1};
o.Kb=function(a){Rc(this.Fa);this.f&&bd(this.f);if(a.target!=this.g)this.g=a.target||n,this.i&&(this.i.start(),S(this.l,this.i,"tick",this.wb)),this.Ka=this.O(),od(this.ba,this.g),S(this.l,this.ba,"key",this.vb),A&&S(this.l,this.g,"keypress",this.ub)};o.tc=function(){if(this.g)Qc(this.l,this.ba,"key",this.vb),this.ba.detach(),Qc(this.l,this.g,"keyup",this.gc),A&&Qc(this.l,this.g,"keypress",this.ub),this.I&&zd(this),this.g=n,this.i&&(this.i.stop(),Qc(this.l,this.i,"tick",this.wb)),this.f&&cd(this.f)};
o.wb=function(){this.update()};o.uc=function(a){this.Kb(a)};o.vb=function(a){this.zb=a.keyCode;this.f&&yd(this,a)};o.rb=function(){this.I&&this.zb!=229&&zd(this)};o.sb=function(a){this.I&&(a.keyCode==13||a.keyCode==77&&a.ctrlKey)&&zd(this)};var zd=function(a){if(a.I)a.I=!1,Qc(a.l,a.g,"keypress",a.rb),Qc(a.l,a.g,"keyup",a.sb)};X.prototype.ub=function(a){xd(this,a)};
X.prototype.update=function(a){if(a||this.g&&this.O()!=this.Ka){if(a||!this.Na){var b,a=md(this.g);b=this.O();a=wd(this,b)[vd(this,b,a)];b=this.nb?String(a).replace(this.nb,""):a;if(this.f&&(this.f.j=this.g,a=this.f,a.q!=b)){a.q=b;b=a.eb;var c=a.q,d=a.Ab,e=t(a.hc,a),f=hd(b,c,d);f.length==0&&b.bc&&(f=id(b,c,d));e(c,f);bd(a)}}this.Ka=this.O()}this.Na=!1};
var vd=function(a,b,c){a=wd(a,b);if(c==b.length)return a.length-1;for(var d=b=0,e=0;d<a.length&&e<c;d++)e+=a[d].length,b=d;return b},wd=function(a,b){if(!a.X)return[b];for(var c=String(b).split(""),d=[],e=[],f=0,g=!1;f<c.length;f++)if(a.Bb&&a.Bb.indexOf(c[f])!=-1){if(a.Nc&&!g)d.push(e.join("")),e.length=0;e.push(c[f]);g=!g}else!g&&a.ha.indexOf(c[f])!=-1?(e.push(c[f]),d.push(e.join("")),e.length=0):e.push(c[f]);d.push(e.join(""));return d};var Y=function(a,b,c,d,e){Q.call(this,b,c,d,e);this.element=a};w(Y,Q);Y.prototype.Ba=aa;Y.prototype.Wa=function(){this.Ba();Y.d.Wa.call(this)};Y.prototype.aa=function(){this.Ba();Y.d.aa.call(this)};Y.prototype.S=function(){this.Ba();Y.d.S.call(this)};var Ad=function(a,b,c,d,e){typeof b=="number"&&(b=[b]);typeof c=="number"&&(c=[c]);Y.call(this,a,b,c,d,e);(b.length!=1||c.length!=1)&&h(Error("Start and end points must be 1D"))};w(Ad,Y);
Ad.prototype.Ba=function(){var a=this.coords[0],b=this.element.style;if("opacity"in b)b.opacity=a;else if("MozOpacity"in b)b.MozOpacity=a;else if("filter"in b)b.filter=a===""?"":"alpha(opacity="+a*100+")"};Ad.prototype.show=function(){this.element.style.display=""};var Bd=function(a,b,c){Ad.call(this,a,1,0,b,c)};w(Bd,Ad);Bd.prototype.S=function(){this.show();Bd.d.S.call(this)};Bd.prototype.aa=function(){this.element.style.display="none";Bd.d.aa.call(this)};
var Cd=function(a,b,c){Ad.call(this,a,0,1,b,c)};w(Cd,Ad);Cd.prototype.S=function(){this.show();Cd.d.S.call(this)};var Z=function(a,b,c,d){this.u=a||document.body;this.e=nb(this.u);this.Wb=!a;this.a=n;this.q="";this.h=[];this.gb=this.pa=-1;this.t=!1;this.className="ac-renderer";this.Ga="ac-row";this.mb="active";this.hb="ac-active";this.Yb="ac-highlighted";this.da=b||n;this.Vb=d!=n?d:!0;this.Ja=!1;this.Xb=c!=n?c:!1;this.Ia=n;this.na=!1;this.qa=0};w(Z,P);Z.prototype.b=function(){return this.a};Z.prototype.Sa=function(a,b,c){this.q=b;this.h=a;this.pa=-1;this.gb=u();this.j=c;this.fa=[];Dd(this)};
Z.prototype.C=function(){this.j&&this.j.setAttribute("aria-activedescendant","");if(this.t)this.t=!1,this.qa>0?(new Bd(this.a,this.qa)).play():Dc(this.a,!1)};Z.prototype.show=function(){if(!this.t)this.t=!0,this.qa>0?(new Cd(this.a,this.qa)).play():Dc(this.a,!0)};
var Fd=function(a,b){Ed(a);a.pa=b;if(b>=0&&b<a.a.childNodes.length){var c=a.fa[b];kb(c,a.hb,a.mb);a.j&&a.j.setAttribute("aria-activedescendant",c?c.id:"");var d=a.a,e=Ac(c),f=Ac(d),g;if(A){var j=Hc(d,"borderLeft");g=Hc(d,"borderRight");var k=Hc(d,"borderTop"),l=Hc(d,"borderBottom");g=new vc(k,g,l,j)}else j=wc(d,"borderLeftWidth"),g=wc(d,"borderRightWidth"),k=wc(d,"borderTopWidth"),l=wc(d,"borderBottomWidth"),g=new vc(parseFloat(k),parseFloat(g),parseFloat(l),parseFloat(j));j=e.x-f.x-g.left;e=e.y-
f.y-g.top;f=d.clientHeight-c.offsetHeight;d.scrollLeft+=Math.min(j,Math.max(j-(d.clientWidth-c.offsetWidth),0));d.scrollTop+=Math.min(e,Math.max(e-f,0))}},Ed=function(a){a.pa>=0&&lb(a.fa[a.pa],a.hb,a.mb)};Z.prototype.r=function(a){if(a==-1)Fd(this,-1);else for(var b=0;b<this.h.length;b++)if(this.h[b].id==a){Fd(this,b);break}};
var Gd=function(a){if(!a.a){var b=a.e.W("div",{style:"display:none"});a.a=b;kb(b,a.className);jd(b,"listbox");b.id=Tc(Sc.oa());a.j&&(jd(a.j,"combobox"),a.j.setAttribute("aria-autocomplete","list"),a.j.setAttribute("aria-haspopup",!0));a.e.appendChild(a.u,b);N(b,"click",a.ib,!1,a);N(b,"mousedown",a.kb,!1,a);N(a.e.w,"mousedown",a.jb,!1,a);N(b,"mouseover",a.lb,!1,a)}},Dd=function(a){Gd(a);if(a.na)a.a.style.visibility="hidden";a.fa.length=0;a.e.pb(a.a);if(a.da&&a.da.qb)a.da.qb(a);else{var b=n;hc(a.h,
function(a){var d=this.q,e=this.e.W("div",{className:this.Ga,id:Tc(Sc.oa())});jd(e,"option");if(!this.da||!this.da.Uc)e.innerHTML=ra(a.data.toString());d&&this.Vb&&Hd(this,e,d);kb(e,this.Ga);this.fa.push(e);a=e;this.na?this.a.insertBefore(a,b):this.e.appendChild(this.a,a);b=a},a)}a.h.length==0?a.C():(a.show(),Id(a.a),Jd(a),Fc(a.a))},Jd=function(a){if(a.j&&a.Wb){var b=Ac(a.j),c=Cc(a.j),d=Cc(yc(a.j)),e=Cc(a.a);b.y=a.na?b.y-e.height:b.y+c.height;(a.Xb||b.x+e.width>d.width)&&a.Ia!="LEFT"?(b.x=b.x+c.width-
e.width,a.Ia="RIGHT"):a.Ia="LEFT";var c=a.a,f,d=Ac(c);if(b instanceof Fa)f=b.y,b=b.x;b=c.offsetLeft+(b-d.x);e=c.offsetTop+(f-d.y);d=B&&(Qa||Xa)&&D("1.9");b instanceof Fa?(f=b.x,b=b.y):(f=b,b=e);c.style.left=Bc(f,d);c.style.top=Bc(b,d);if(a.na)a.a.style.visibility="visible"}};
Z.prototype.c=function(){Z.d.c.call(this);if(this.a)Zb(this.a,"click",this.ib,!1,this),Zb(this.a,"mousedown",this.kb,!1,this),Zb(this.e.w,"mousedown",this.jb,!1,this),Zb(this.a,"mouseover",this.lb,!1,this),this.e.removeNode(this.a),this.a=n,this.t=!1;delete this.u};
var Id=function(a){if(B&&Qa)a.style.width="",a.style.overflow="visible",a.style.width=a.offsetWidth,a.style.overflow="auto"},Hd=function(a,b,c){if(b.nodeType==3){var d=n;r(c)&&c.length>1&&!a.Ja&&(d=Da(c,1));c=Kd(a,c);if(c.length!=0){for(var e=b.nodeValue,f=RegExp("(.*?)(^|\\W+)("+c+")","gi"),c=[],g=0,j=f.exec(e),k=0;j;)k++,c.push(j[1]),c.push(j[2]),c.push(j[3]),g=f.lastIndex,j=f.exec(e);c.push(e.substring(g));if(c.length>1){d=!a.Ja?1:k;for(e=0;e<d;e++)f=3*e,b.nodeValue=c[f]+c[f+1],g=a.e.createElement("b"),
g.className=a.Yb,a.e.appendChild(g,a.e.createTextNode(c[f+2])),g=b.parentNode.insertBefore(g,b.nextSibling),b.parentNode.insertBefore(a.e.createTextNode(""),g.nextSibling),b=g.nextSibling;a=Da(c,d*3);b.nodeValue=a.join("")}else d&&Hd(a,b,d)}}else for(b=b.firstChild;b;)d=b.nextSibling,Hd(a,b,c),b=d},Kd=function(a,b){var c="";if(!b)return c;a.Ja?r(b)?(c=ya(b,function(a){return!/^[\s\xa0]*$/.test(a==n?"":String(a))}),c=za(c,sa),c=c.join("|")):(c=b.replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,""),c=
sa(c),c=c.replace(/ /g,"|")):c=r(b)?b.length>0?sa(b[0]):"":sa(b);return c},Ld=function(a,b){for(;b&&b!=a.a&&!(z(jb(b),a.Ga)>=0);)b=b.parentNode;return b?z(a.fa,b):-1};Z.prototype.ib=function(a){var b=Ld(this,a.target);b>=0&&this.dispatchEvent({type:"select",ua:this.h[b].id});a.stopPropagation()};Z.prototype.kb=function(a){this.dispatchEvent("canceldismiss");a.stopPropagation();a.preventDefault()};Z.prototype.jb=function(a){this.j==a.target?(Ed(this),a.stopPropagation()):this.dispatchEvent("dismiss")};
Z.prototype.lb=function(a){a=Ld(this,a.target);a>=0&&!(u()-this.gb<300)&&this.dispatchEvent({type:"hilite",ua:this.h[a].id})};var $=function(a,b,c,d,e){this.ob=[];this.Mb=[];for(var f=0;f<=128;f++)f>=48&&f<=57||f>=65&&f<=90||f>=97&&f<=122||f==95||(this.Mb[f]="%25"+"0123456789ABCDEF".charAt(f>>4)+"0123456789ABCDEF".charAt(f&15));this.Lb=a;this.Gc=b;this.Fc=c;this.ab=d;this.Ic=e==1?!0:!1;this.Aa=[];this.Oa={};this.xb={}};w($,I);var Md="gsa.search.DynNavManager".split("."),Nd=q;!(Md[0]in Nd)&&Nd.execScript&&Nd.execScript("var "+Md[0]);
for(var Od;Md.length&&(Od=Md.shift());)!Md.length&&$!==i?Nd[Od]=$:Nd=Nd[Od]?Nd[Od]:Nd[Od]={};
$.prototype.U=function(){for(var a=G("dyn_nav_col"),a=ob("UL","dn-attr-more",a),b=0;b<a.length;b++){var c=a[b],d=ob("DIV","dn-zippy-hdr",c)[0],e=H("INPUT",{"class":"dn-zippy-input"}),f=H("DIV",n,e);d.parentNode&&d.parentNode.insertBefore(f,d.nextSibling);var g=new U("search...");Vc(g,e);d=new Kc(d,f,!1);N(d,"toggle",t(function(a){$c(a)&&a.Ma("");var b=$c(a);a.Ra=!0;a.b().focus();if(!b)a.b().value=a.Y;a.b().select();a.J&&Pc(a.J,a.b(),"click",a.La);lc(a.lc,a)},n,g));Aa(this.ob,d);for(var g=zb(ob("LABEL",
"dn-name",c)[0]),d=Pd(this,g),j=ob("A","dn-attr-v",c),c=[],f=0;f<j.length;f++)c[f]=zb(j[f]);if((j=this.Oa[g])&&j.length>0)for(var k=0;k<j.length-1;k++)c[f++]=j[k][0]+Qd(this,j[k][1]);f=new Rd(d,this);ud(f,e);Sd(c,f);e=Number(zb(G(g+"_total")));c=Number(zb(G(g+"_total_left")));this.xb[g]={escaped:d,pos:0,total:e,total_left:c,total_left_original:c,to_show:10}}N(window,"unload",t(this.k,this))};$.prototype.init=$.prototype.U;
$.prototype.Sc=function(a,b,c){var d=G("more_"+a),e=G("less_"+a),f=G("disp_"+a),g=this.xb[a];if(b){var j=this.Oa[a],c=g.to_show;g.total_left<c&&(c=g.total_left);for(var k=H("UL",{"class":"dn-attr-hidden"}),b=g.pos;b<g.pos+c;b++){var l="inmeta:"+g.escaped+"%3D"+Pd(this,j[b][0]),v=Qd(this,j[b][1]),m=z(this.Aa,l);if(m!=-1){var p="";xa(this.Aa,function(a,b){b!=m&&(p+=a+"+")});p=p.substring(0,p.length-1);l=this.ab+"&q="+this.Fc;p!=""&&(l+="+"+p+"&dnavs="+p);l=H("A",{"class":"dn-img dn-r-img",href:"GSASearchresults.aspx?"+
l,title:"Clear"});v=H("SPAN",{"class":"dn-overflow dn-inline-block",title:j[b][0],style:"width: 86%;"},j[b][0]+v);ub(k,H("LI",n,l,v))}else v=H("SPAN","dn-attr-c",v),l=H("A",{"class":"dn-attr-v",href:Td(this,l),title:j[b][0]},j[b][0],v),ub(k,H("LI",n,l))}j=G(a+"_more_less");a=H("LI",{"class":a+"_dn"},k);j.parentNode&&j.parentNode.insertBefore(a,j);a=g.total_left-c;f.innerHTML=a+" More";g.pos=b;g.to_show*=2;g.total_left=a;e.className="dn-inline-block";if(a<=0)d.className="dn-hidden"}else{a=pb(a+"_dn",
G(a));for(b=0;b<a.length;b++)vb(a[b]),a[b]=n;g.pos=0;g.total_left=g.total_left_original;g.to_show=10;f.innerHTML=c+" More";d.className="dn-inline-block";e.className="dn-hidden"}};$.prototype.displayMore=$.prototype.Sc;$.prototype.Qc=function(a,b){this.Oa[a]=b};$.prototype.addAttrValues=$.prototype.Qc;$.prototype.Rc=function(a){Aa(this.Aa,a)};$.prototype.addSelectedAttr=$.prototype.Rc;var Sd=function(a,b){var c=new gd(a),d=new Z,c=new V(c,d,b);c.Ab=15;b.f=c};
$.prototype.c=function(){xa(this.ob,function(a){a.k()});$.d.c.call(this)};
var Td=function(a,b){var c="dnavs=";a.Lb!=""&&(c+=a.Lb+"+");var sender = (a && a.target) || (window.event && window.event.srcElement);c+=encodeURIComponent(b);var d="GSASearchresults.aspx?";a.ab!=""&&(d+=a.ab+"&");d+="q="+a.Gc+"+"+encodeURIComponent(b)+"&"+c;return d},Qd=function(a,b){var c=" (";a.Ic&&(c+="> ");c+=b+")";return c},Pd=function(a,b){for(var c="",d=0;d<b.length;d++){var e=b.charCodeAt(d);c+=e>128?encodeURIComponent(b.charAt(d)):e>=48&&e<=57||e>=65&&e<=90||e>=97&&e<=122||e==95?b.charAt(d):a.Mb[e]}return c},Rd=function(a,b){X.call(this,n,n,!1);this.Ac=a;this.zc=b};w(Rd,X);
Rd.prototype.Qa=function(a){var b;a:{b=this.zc;var c=a.substring(0,a.lastIndexOf(" ("));if(c!=""&&(c="inmeta:"+this.Ac+"%3D"+Pd(b,c),z(b.Aa,c)==-1)){b=Td(b,c);break a}b=""}if(b!="")Rd.d.Qa.call(this,a,!1),window.location.href=b;return!1};
