//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACLTestProject.GssAclTestProjectReference2010 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="gssAcl.generated.sharepoint.connector.enterprise.google.com", ConfigurationName="GssAclTestProjectReference2010.GssAclMonitorSoap")]
    public interface GssAclMonitorSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="gssAcl.generated.sharepoint.connector.enterprise.google.com/CheckConnectivity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string CheckConnectivity();
        
        [System.ServiceModel.OperationContractAttribute(Action="gssAcl.generated.sharepoint.connector.enterprise.google.com/GetAclForUrls", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GssAclBaseResult))]
        ACLTestProject.GssAclTestProjectReference2010.GssGetAclForUrlsResult GetAclForUrls(string[] urls);
        
        [System.ServiceModel.OperationContractAttribute(Action="gssAcl.generated.sharepoint.connector.enterprise.google.com/GetAclChangesSinceTok" +
            "en", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GssAclBaseResult))]
        ACLTestProject.GssAclTestProjectReference2010.GssGetAclChangesSinceTokenResult GetAclChangesSinceToken(string fromChangeToken, string toChangeToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="gssAcl.generated.sharepoint.connector.enterprise.google.com/ResolveSPGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GssAclBaseResult))]
        ACLTestProject.GssAclTestProjectReference2010.GssResolveSPGroupResult ResolveSPGroup(string[] groupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="gssAcl.generated.sharepoint.connector.enterprise.google.com/GetListsWithInheritin" +
            "gRoleAssignments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GssAclBaseResult))]
        string[] GetListsWithInheritingRoleAssignments();
        
        [System.ServiceModel.OperationContractAttribute(Action="gssAcl.generated.sharepoint.connector.enterprise.google.com/GetListItemsWithInher" +
            "itingRoleAssignments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GssAclBaseResult))]
        ACLTestProject.GssAclTestProjectReference2010.GssGetListItemsWithInheritingRoleAssignments GetListItemsWithInheritingRoleAssignments(string listGuId, int rowLimit, int lastItemId);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gssAcl.generated.sharepoint.connector.enterprise.google.com")]
    public partial class GssGetAclForUrlsResult : GssAclBaseResult {
        
        private GssAcl[] allAclsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public GssAcl[] AllAcls {
            get {
                return this.allAclsField;
            }
            set {
                this.allAclsField = value;
                this.RaisePropertyChanged("AllAcls");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gssAcl.generated.sharepoint.connector.enterprise.google.com")]
    public partial class GssAcl : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string entityUrlField;
        
        private string ownerField;
        
        private GssAce[] allAceField;
        
        private string logMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EntityUrl {
            get {
                return this.entityUrlField;
            }
            set {
                this.entityUrlField = value;
                this.RaisePropertyChanged("EntityUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
                this.RaisePropertyChanged("Owner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public GssAce[] AllAce {
            get {
                return this.allAceField;
            }
            set {
                this.allAceField = value;
                this.RaisePropertyChanged("AllAce");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string LogMessage {
            get {
                return this.logMessageField;
            }
            set {
                this.logMessageField = value;
                this.RaisePropertyChanged("LogMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gssAcl.generated.sharepoint.connector.enterprise.google.com")]
    public partial class GssAce : object, System.ComponentModel.INotifyPropertyChanged {
        
        private GssPrincipal principalField;
        
        private GssSharepointPermission permissionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public GssPrincipal Principal {
            get {
                return this.principalField;
            }
            set {
                this.principalField = value;
                this.RaisePropertyChanged("Principal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public GssSharepointPermission Permission {
            get {
                return this.permissionField;
            }
            set {
                this.permissionField = value;
                this.RaisePropertyChanged("Permission");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gssAcl.generated.sharepoint.connector.enterprise.google.com")]
    public partial class GssPrincipal : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private PrincipalType typeField;
        
        private GssPrincipal[] membersField;
        
        private string logMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public PrincipalType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public GssPrincipal[] Members {
            get {
                return this.membersField;
            }
            set {
                this.membersField = value;
                this.RaisePropertyChanged("Members");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string LogMessage {
            get {
                return this.logMessageField;
            }
            set {
                this.logMessageField = value;
                this.RaisePropertyChanged("LogMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gssAcl.generated.sharepoint.connector.enterprise.google.com")]
    public enum PrincipalType {
        
        /// <remarks/>
        USER,
        
        /// <remarks/>
        DOMAINGROUP,
        
        /// <remarks/>
        SPGROUP,
        
        /// <remarks/>
        NA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gssAcl.generated.sharepoint.connector.enterprise.google.com")]
    public partial class GssAclChange : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ObjectType changedObjectField;
        
        private SPChangeType changeTypeField;
        
        private string hintField;
        
        private bool isEffectiveInCurrentWebField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ObjectType ChangedObject {
            get {
                return this.changedObjectField;
            }
            set {
                this.changedObjectField = value;
                this.RaisePropertyChanged("ChangedObject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SPChangeType ChangeType {
            get {
                return this.changeTypeField;
            }
            set {
                this.changeTypeField = value;
                this.RaisePropertyChanged("ChangeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Hint {
            get {
                return this.hintField;
            }
            set {
                this.hintField = value;
                this.RaisePropertyChanged("Hint");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool IsEffectiveInCurrentWeb {
            get {
                return this.isEffectiveInCurrentWebField;
            }
            set {
                this.isEffectiveInCurrentWebField = value;
                this.RaisePropertyChanged("IsEffectiveInCurrentWeb");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gssAcl.generated.sharepoint.connector.enterprise.google.com")]
    public enum ObjectType {
        
        /// <remarks/>
        NA,
        
        /// <remarks/>
        SECURITY_POLICY,
        
        /// <remarks/>
        ADMINISTRATORS,
        
        /// <remarks/>
        GROUP,
        
        /// <remarks/>
        USER,
        
        /// <remarks/>
        WEB,
        
        /// <remarks/>
        LIST,
        
        /// <remarks/>
        ITEM,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gssAcl.generated.sharepoint.connector.enterprise.google.com")]
    public enum SPChangeType {
        
        /// <remarks/>
        Add,
        
        /// <remarks/>
        Update,
        
        /// <remarks/>
        Delete,
        
        /// <remarks/>
        Rename,
        
        /// <remarks/>
        MoveAway,
        
        /// <remarks/>
        MoveInto,
        
        /// <remarks/>
        Restore,
        
        /// <remarks/>
        RoleAdd,
        
        /// <remarks/>
        RoleDelete,
        
        /// <remarks/>
        RoleUpdate,
        
        /// <remarks/>
        AssignmentAdd,
        
        /// <remarks/>
        AssignmentDelete,
        
        /// <remarks/>
        MemberAdd,
        
        /// <remarks/>
        MemberDelete,
        
        /// <remarks/>
        SystemUpdate,
        
        /// <remarks/>
        Navigation,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gssAcl.generated.sharepoint.connector.enterprise.google.com")]
    public partial class GssAclChangeCollection : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string changeTokenField;
        
        private GssAclChange[] changesField;
        
        private string logMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ChangeToken {
            get {
                return this.changeTokenField;
            }
            set {
                this.changeTokenField = value;
                this.RaisePropertyChanged("ChangeToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public GssAclChange[] Changes {
            get {
                return this.changesField;
            }
            set {
                this.changesField = value;
                this.RaisePropertyChanged("Changes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LogMessage {
            get {
                return this.logMessageField;
            }
            set {
                this.logMessageField = value;
                this.RaisePropertyChanged("LogMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gssAcl.generated.sharepoint.connector.enterprise.google.com")]
    public partial class GssSharepointPermission : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] allowedPermissionsField;
        
        private string[] deniedPermissionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] AllowedPermissions {
            get {
                return this.allowedPermissionsField;
            }
            set {
                this.allowedPermissionsField = value;
                this.RaisePropertyChanged("AllowedPermissions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public string[] DeniedPermission {
            get {
                return this.deniedPermissionField;
            }
            set {
                this.deniedPermissionField = value;
                this.RaisePropertyChanged("DeniedPermission");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GssGetListItemsWithInheritingRoleAssignments))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GssResolveSPGroupResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GssGetAclChangesSinceTokenResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GssGetAclForUrlsResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gssAcl.generated.sharepoint.connector.enterprise.google.com")]
    public abstract partial class GssAclBaseResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string siteCollectionUrlField;
        
        private System.Guid siteCollectionGuidField;
        
        private string logMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SiteCollectionUrl {
            get {
                return this.siteCollectionUrlField;
            }
            set {
                this.siteCollectionUrlField = value;
                this.RaisePropertyChanged("SiteCollectionUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid SiteCollectionGuid {
            get {
                return this.siteCollectionGuidField;
            }
            set {
                this.siteCollectionGuidField = value;
                this.RaisePropertyChanged("SiteCollectionGuid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LogMessage {
            get {
                return this.logMessageField;
            }
            set {
                this.logMessageField = value;
                this.RaisePropertyChanged("LogMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gssAcl.generated.sharepoint.connector.enterprise.google.com")]
    public partial class GssGetListItemsWithInheritingRoleAssignments : GssAclBaseResult {
        
        private string docXmlField;
        
        private bool moreDocsField;
        
        private int lastIdVisitedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DocXml {
            get {
                return this.docXmlField;
            }
            set {
                this.docXmlField = value;
                this.RaisePropertyChanged("DocXml");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool MoreDocs {
            get {
                return this.moreDocsField;
            }
            set {
                this.moreDocsField = value;
                this.RaisePropertyChanged("MoreDocs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int LastIdVisited {
            get {
                return this.lastIdVisitedField;
            }
            set {
                this.lastIdVisitedField = value;
                this.RaisePropertyChanged("LastIdVisited");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gssAcl.generated.sharepoint.connector.enterprise.google.com")]
    public partial class GssResolveSPGroupResult : GssAclBaseResult {
        
        private GssPrincipal[] prinicpalsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public GssPrincipal[] Prinicpals {
            get {
                return this.prinicpalsField;
            }
            set {
                this.prinicpalsField = value;
                this.RaisePropertyChanged("Prinicpals");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gssAcl.generated.sharepoint.connector.enterprise.google.com")]
    public partial class GssGetAclChangesSinceTokenResult : GssAclBaseResult {
        
        private GssAclChangeCollection allChangesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public GssAclChangeCollection AllChanges {
            get {
                return this.allChangesField;
            }
            set {
                this.allChangesField = value;
                this.RaisePropertyChanged("AllChanges");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface GssAclMonitorSoapChannel : ACLTestProject.GssAclTestProjectReference2010.GssAclMonitorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GssAclMonitorSoapClient : System.ServiceModel.ClientBase<ACLTestProject.GssAclTestProjectReference2010.GssAclMonitorSoap>, ACLTestProject.GssAclTestProjectReference2010.GssAclMonitorSoap {
        
        public GssAclMonitorSoapClient() {
        }
        
        public GssAclMonitorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GssAclMonitorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GssAclMonitorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GssAclMonitorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CheckConnectivity() {
            return base.Channel.CheckConnectivity();
        }
        
        public ACLTestProject.GssAclTestProjectReference2010.GssGetAclForUrlsResult GetAclForUrls(string[] urls) {
            return base.Channel.GetAclForUrls(urls);
        }
        
        public ACLTestProject.GssAclTestProjectReference2010.GssGetAclChangesSinceTokenResult GetAclChangesSinceToken(string fromChangeToken, string toChangeToken) {
            return base.Channel.GetAclChangesSinceToken(fromChangeToken, toChangeToken);
        }
        
        public ACLTestProject.GssAclTestProjectReference2010.GssResolveSPGroupResult ResolveSPGroup(string[] groupId) {
            return base.Channel.ResolveSPGroup(groupId);
        }
        
        public string[] GetListsWithInheritingRoleAssignments() {
            return base.Channel.GetListsWithInheritingRoleAssignments();
        }
        
        public ACLTestProject.GssAclTestProjectReference2010.GssGetListItemsWithInheritingRoleAssignments GetListItemsWithInheritingRoleAssignments(string listGuId, int rowLimit, int lastItemId) {
            return base.Channel.GetListItemsWithInheritingRoleAssignments(listGuId, rowLimit, lastItemId);
        }
    }
}
